### ISSUE TITLE
S400

### ISSUE THREAD

**Issue by flashbackboi** [yuankong666/Ultimate-RAT-Collection#3]
its not working pls fix it

**Comment by yuankong666** [comment]
I cannot fix this, I archive as-is.

I see the issue, it seems to crash while launching on Windows 10, but runs normally on Windows 7.
Try looking around in dnSpy, the executable is relatively unobfuscated.

**Comment by flashbackboi** [comment]
> I cannot fix this, I archive as-is.
> 
> I see the issue, it seems to crash while launching on Windows 10, but runs normally on Windows 7. Try looking around in dnSpy, the executable is relatively unobfuscated.
> 
> I assume for now that it's some sort of Anti-VM function.

i tried on normal windows on win 11 still no fix
